# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ExampleGoreleaser < Formula
  desc "Lightweight Kubernetes conformance tests runner"
  homepage "https://github.com/reetasingh/example-goreleaser"
  version "3.0.3"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reetasingh/example-goreleaser/releases/download/v3.0.3/example-goreleaser_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "b463902b2190acc4d3085c4f08ae0d2f1ebd4d82bf3901dc97f9dc736d0e5117"

      def install
        system "go", "build", *std_go_args(ldflags: "-s -w")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reetasingh/example-goreleaser/releases/download/v3.0.3/example-goreleaser_Darwin_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "f2d8786f42615316dee79584ee651fa739da611ec71088fa266e18f2dd41d10b"

      def install
        system "go", "build", *std_go_args(ldflags: "-s -w")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/reetasingh/example-goreleaser/releases/download/v3.0.3/example-goreleaser_Linux_x86_64.tar.gz", using: CurlDownloadStrategy,
        headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "5df27e209fc42fabc24584e3e6a8e5f11e5185c835e5d3f0373688de8bcc65ad"

      def install
        system "go", "build", *std_go_args(ldflags: "-s -w")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reetasingh/example-goreleaser/releases/download/v3.0.3/example-goreleaser_Linux_arm64.tar.gz", using: CurlDownloadStrategy,
        headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "749fd717c002e051171c9795d6f98996425e82c287aaf5094864556458400697"

      def install
        system "go", "build", *std_go_args(ldflags: "-s -w")
      end
    end
  end
end
